server:
  port: 7001

#eureka配置
eureka:
  instance:
    hostname: eureka7001 #eureka服务端实例名称
  client:
    register-with-eureka: false  #表示是否向eureka注册中心注册自己
    fetch-registry: false #如果为false，则表示自己为注册中心
    service-url: #监控页面
      #单机模式下 defaultZone: http://${eureka.instance.hostname}:${server.port}/erueka/
      #集群关联模式下
      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
